[package]
name = "panic_repro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv = {version = "0.11.0"}
riscv-rt = {version = "0.12.0"}
spinning_top = {version = "0.3.0"}
